In [128]:
import numpy as np
import pandas as pd

In [189]:
file_path = "../00_data/pop_municipal_subprov_areas_2001_2011.xlsx"
# Read the population data from Excel file and sheet "Mun Name Sort"
# Skip the first two rows as they contain Headings
df_pop_2001_2011 = pd.read_excel(file_path, sheet_name="Mun Name Sort", header=2)

In [190]:
#Check the columns in the dataframe & drop the empty column
print(df_pop_2001_2011.columns)
df_pop_2001_2011 = df_pop_2001_2011.drop(columns=['Unnamed: 13'])

Index(['Name', 'Area Type', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', 'Unnamed: 13',
       '2001-02 Changes', '2002-03 Changes', '2003-04 Changes',
       '2004-05 Changes', '2005-06 Changes', '2006-07 Changes',
       '2007-08 Changes', '2008-09 Changes', '2009-10 Changes',
       '2010-11 Changes'],
      dtype='object')

In [131]:
print(df_pop_2001_2011.columns)
df_pop_2001_2011.info()

Index(['Name', 'Area Type', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2001-02 Changes',
       '2002-03 Changes', '2003-04 Changes', '2004-05 Changes',
       '2005-06 Changes', '2006-07 Changes', '2007-08 Changes',
       '2008-09 Changes', '2009-10 Changes', '2010-11 Changes'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             182 non-null    object
 1   Area Type        162 non-null    object
 2   2001             165 non-null    float64
 3   2002             165 non-null    float64
 4   2003             165 non-null    float64
 5   2004             165 non-null    float64
 6   2005             165 non-null    float64
 7   2006             165 non-null    float64
 8   2007             165 non-null    float64
 9   2008             165 non-null    float64
 10  2009             165 non-null    float64
 11  2010             165 non-null    float64
 12  2011             165 non-null    float64
 13  2001-02 Changes  165 non-null    float64
 14  2002-03 Changes  165 non-null    float64
 15  2003-04 Changes  165 non-null    float64
 16  2004-05 Changes  165 non-null    float64
 17  2005-06 Changes  165 non-null    float64
 18  2006-07 Changes  165 non-null    float64
 19  2007-08 Changes  165 non-null    float64
 20  2008-09 Changes  165 non-null    float64
 21  2009-10 Changes  165 non-null    float64
 22  2010-11 Changes  165 non-null    float64
dtypes: float64(21), object(2)
memory usage: 33.6+ KB

In [191]:
file_path = "../00_data/pop_municipal_subprov_areas_2011_2024.xlsx"
# Read the population data from Excel file and sheet "Mun Name Sort"
# Skip the first two rows as they contain Headings
df_pop_2011_2024 = pd.read_excel(file_path, sheet_name="Mun Name Sort", header=2)

In [192]:
df_pop_2011_2024.info()
df_pop_2011_2024 = df_pop_2011_2024.drop(columns=['Unnamed: 16'])
df_pop_2011_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             182 non-null    object
 1   Area Type        162 non-null    object
 2   2011             165 non-null    float64
 3   2012             165 non-null    float64
 4   2013             165 non-null    float64
 5   2014             165 non-null    float64
 6   2015             165 non-null    float64
 7   2016             165 non-null    float64
 8   2017             165 non-null    float64
 9   2018             165 non-null    float64
 10  2019             165 non-null    float64
 11  2020             165 non-null    float64
 12  2021             165 non-null    float64
 13  2022             165 non-null    float64
 14  2023             165 non-null    float64
 15  2024             165 non-null    float64
 16  Unnamed: 16      0 non-null      float64
 17  2011-12 Changes  165 non-null    float64
 18  2012-13 Changes  165 non-null    float64
 19  2013-14 Changes  165 non-null    float64
 20  2014-15 Changes  165 non-null    float64
 21  2015-16 Changes  165 non-null    float64
 22  2016-17 Changes  165 non-null    float64
 23  2017-18 Changes  165 non-null    float64
 24  2018-19 Changes  165 non-null    float64
 25  2019-20 Changes  165 non-null    float64
 26  2020-21 Changes  165 non-null    float64
 27  2021-22 Changes  165 non-null    float64
 28  2022-23 Changes  165 non-null    float64
 29  2023-24 Changes  165 non-null    float64
dtypes: float64(28), object(2)
memory usage: 43.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             182 non-null    object
 1   Area Type        162 non-null    object
 2   2011             165 non-null    float64
 3   2012             165 non-null    float64
 4   2013             165 non-null    float64
 5   2014             165 non-null    float64
 6   2015             165 non-null    float64
 7   2016             165 non-null    float64
 8   2017             165 non-null    float64
 9   2018             165 non-null    float64
 10  2019             165 non-null    float64
 11  2020             165 non-null    float64
 12  2021             165 non-null    float64
 13  2022             165 non-null    float64
 14  2023             165 non-null    float64
 15  2024             165 non-null    float64
 16  2011-12 Changes  165 non-null    float64
 17  2012-13 Changes  165 non-null    float64
 18  2013-14 Changes  165 non-null    float64
 19  2014-15 Changes  165 non-null    float64
 20  2015-16 Changes  165 non-null    float64
 21  2016-17 Changes  165 non-null    float64
 22  2017-18 Changes  165 non-null    float64
 23  2018-19 Changes  165 non-null    float64
 24  2019-20 Changes  165 non-null    float64
 25  2020-21 Changes  165 non-null    float64
 26  2021-22 Changes  165 non-null    float64
 27  2022-23 Changes  165 non-null    float64
 28  2023-24 Changes  165 non-null    float64
dtypes: float64(27), object(2)
memory usage: 42.3+ KB

In [193]:
df_pop_2011_2024['Name']

0                                             Abbotsford
1                                              Alert Bay
2                                                 Anmore
3                                              Armstrong
4                                               Ashcroft
                             ...
181    Qathet Regional District (27000) was formerly ...
182    North Coast Regional District (47000) was form...
183    Jumbo Glacier Mountain Resort Municipality has...
184    All figures correspond to municipal boundaries...
185    All figures are as of July 1st of the year sta...
Name: Name, Length: 186, dtype: object

In [194]:
print(df_pop_2011_2024.tail(30)) #161
print(df_pop_2001_2011.tail(30)) #161

df_pop_2011_2024 = df_pop_2011_2024.iloc[:161]
df_pop_2001_2011 = df_pop_2001_2011.iloc[:161]

#df_pop_2011_2024

                                                  Name Area Type       2011  \
156                                       West Kelowna        CY    31466.0
157                                     West Vancouver        DM    43238.0
158                                           Whistler        DM    10232.0
159                                         White Rock        CY    19544.0
160                                      Williams Lake        CY    11027.0
161                                           Zeballos        VL      127.0
162                                  Muncipality Total       NaN  4012989.0
163                                    Non Muncipality       NaN   490830.0
164                                   British Columbia       NaN  4503819.0
165                                                NaN       NaN        NaN
166                                                NaN       NaN        NaN
167                                            Source:       NaN        NaN
168                                  Statistics Canada       NaN        NaN
169                                                and       NaN        NaN
170             Demographic Analysis Section, BC Stats       NaN        NaN
171                     Ministry of Citizens’ Services       NaN        NaN
172                     Government of British Columbia       NaN        NaN
173                                                NaN       NaN        NaN
174                                     February, 2025       NaN        NaN
175                                                NaN       NaN        NaN
176                                             Notes:       NaN        NaN
177  RD = Regional District, R = Region, RDR = Regi...       NaN        NaN
178  CY = City, T = Town, VL = Village, DM = Distri...       NaN        NaN
179         SGC = Standard Geographical Classification       NaN        NaN
180  Metro Vancouver Regional District (15000) was ...       NaN        NaN
181  Qathet Regional District (27000) was formerly ...       NaN        NaN
182  North Coast Regional District (47000) was form...       NaN        NaN
183  Jumbo Glacier Mountain Resort Municipality has...       NaN        NaN
184  All figures correspond to municipal boundaries...       NaN        NaN
185  All figures are as of July 1st of the year sta...       NaN        NaN

          2012       2013       2014       2015       2016       2017  \
156    31791.0    32347.0    32776.0    33357.0    34040.0    34697.0
157    43418.0    43652.0    43799.0    43769.0    43889.0    43957.0
158    10542.0    10887.0    11457.0    11810.0    12622.0    13322.0
159    19705.0    19761.0    20143.0    20297.0    20643.0    21117.0
160    11100.0    11119.0    11257.0    11236.0    11176.0    11141.0
161      123.0      118.0      115.0      111.0      111.0      116.0
162  4076707.0  4137091.0  4208447.0  4256736.0  4342573.0  4406835.0
163   494159.0   497852.0   504244.0   508736.0   518696.0   527367.0
164  4570866.0  4634943.0  4712691.0  4765472.0  4861269.0  4934202.0
165        NaN        NaN        NaN        NaN        NaN        NaN
166        NaN        NaN        NaN        NaN        NaN        NaN
167        NaN        NaN        NaN        NaN        NaN        NaN
168        NaN        NaN        NaN        NaN        NaN        NaN
169        NaN        NaN        NaN        NaN        NaN        NaN
170        NaN        NaN        NaN        NaN        NaN        NaN
171        NaN        NaN        NaN        NaN        NaN        NaN
172        NaN        NaN        NaN        NaN        NaN        NaN
173        NaN        NaN        NaN        NaN        NaN        NaN
174        NaN        NaN        NaN        NaN        NaN        NaN
175        NaN        NaN        NaN        NaN        NaN        NaN
176        NaN        NaN        NaN        NaN        NaN        NaN
177        NaN        NaN        NaN        NaN        NaN        NaN
178        NaN        NaN        NaN        NaN        NaN        NaN
179        NaN        NaN        NaN        NaN        NaN        NaN
180        NaN        NaN        NaN        NaN        NaN        NaN
181        NaN        NaN        NaN        NaN        NaN        NaN
182        NaN        NaN        NaN        NaN        NaN        NaN
183        NaN        NaN        NaN        NaN        NaN        NaN
184        NaN        NaN        NaN        NaN        NaN        NaN
185        NaN        NaN        NaN        NaN        NaN        NaN

          2018  ...  2014-15 Changes  2015-16 Changes  2016-17 Changes  \
156    35404.0  ...            0.018            0.020            0.019
157    44162.0  ...           -0.001            0.003            0.002
158    13999.0  ...            0.031            0.069            0.055
159    21638.0  ...            0.008            0.017            0.023
160    11284.0  ...           -0.002           -0.005           -0.003
161      120.0  ...           -0.035            0.000            0.045
162  4484616.0  ...            0.011            0.020            0.015
163   536363.0  ...            0.009            0.020            0.017
164  5020979.0  ...            0.011            0.020            0.015
165        NaN  ...              NaN              NaN              NaN
166        NaN  ...              NaN              NaN              NaN
167        NaN  ...              NaN              NaN              NaN
168        NaN  ...              NaN              NaN              NaN
169        NaN  ...              NaN              NaN              NaN
170        NaN  ...              NaN              NaN              NaN
171        NaN  ...              NaN              NaN              NaN
172        NaN  ...              NaN              NaN              NaN
173        NaN  ...              NaN              NaN              NaN
174        NaN  ...              NaN              NaN              NaN
175        NaN  ...              NaN              NaN              NaN
176        NaN  ...              NaN              NaN              NaN
177        NaN  ...              NaN              NaN              NaN
178        NaN  ...              NaN              NaN              NaN
179        NaN  ...              NaN              NaN              NaN
180        NaN  ...              NaN              NaN              NaN
181        NaN  ...              NaN              NaN              NaN
182        NaN  ...              NaN              NaN              NaN
183        NaN  ...              NaN              NaN              NaN
184        NaN  ...              NaN              NaN              NaN
185        NaN  ...              NaN              NaN              NaN

     2017-18 Changes  2018-19 Changes  2019-20 Changes  2020-21 Changes  \
156            0.020            0.016            0.023            0.021
157            0.005            0.011            0.011            0.009
158            0.051            0.066            0.035           -0.044
159            0.025            0.015            0.013            0.015
160            0.013            0.009           -0.005            0.010
161            0.034            0.025            0.033            0.024
162            0.018            0.019            0.013            0.009
163            0.017            0.011            0.010            0.015
164            0.018            0.018            0.013            0.010
165              NaN              NaN              NaN              NaN
166              NaN              NaN              NaN              NaN
167              NaN              NaN              NaN              NaN
168              NaN              NaN              NaN              NaN
169              NaN              NaN              NaN              NaN
170              NaN              NaN              NaN              NaN
171              NaN              NaN              NaN              NaN
172              NaN              NaN              NaN              NaN
173              NaN              NaN              NaN              NaN
174              NaN              NaN              NaN              NaN
175              NaN              NaN              NaN              NaN
176              NaN              NaN              NaN              NaN
177              NaN              NaN              NaN              NaN
178              NaN              NaN              NaN              NaN
179              NaN              NaN              NaN              NaN
180              NaN              NaN              NaN              NaN
181              NaN              NaN              NaN              NaN
182              NaN              NaN              NaN              NaN
183              NaN              NaN              NaN              NaN
184              NaN              NaN              NaN              NaN
185              NaN              NaN              NaN              NaN

     2021-22 Changes  2022-23 Changes  2023-24 Changes
156            0.035            0.024            0.007
157            0.019            0.026            0.026
158            0.023            0.063           -0.027
159            0.041            0.046            0.022
160           -0.013            0.008           -0.001
161            0.023            0.008            0.007
162            0.026            0.034            0.033
163            0.020            0.017            0.007
164            0.025            0.032            0.030
165              NaN              NaN              NaN
166              NaN              NaN              NaN
167              NaN              NaN              NaN
168              NaN              NaN              NaN
169              NaN              NaN              NaN
170              NaN              NaN              NaN
171              NaN              NaN              NaN
172              NaN              NaN              NaN
173              NaN              NaN              NaN
174              NaN              NaN              NaN
175              NaN              NaN              NaN
176              NaN              NaN              NaN
177              NaN              NaN              NaN
178              NaN              NaN              NaN
179              NaN              NaN              NaN
180              NaN              NaN              NaN
181              NaN              NaN              NaN
182              NaN              NaN              NaN
183              NaN              NaN              NaN
184              NaN              NaN              NaN
185              NaN              NaN              NaN

[30 rows x 29 columns]
                                                  Name Area Type       2001  \
156                                       West Kelowna        CY    25477.0
157                                     West Vancouver        DM    42691.0
158                                           Whistler        DM     9405.0
159                                         White Rock        CY    18844.0
160                                      Williams Lake        CY    11660.0
161                                           Zeballos        VL      231.0
162                                  Muncipality Total       NaN  3596765.0
163                                    Non Muncipality       NaN   480131.0
164                                   British Columbia       NaN  4076896.0
165                                                NaN       NaN        NaN
166                                                NaN       NaN        NaN
167                                            Source:       NaN        NaN
168                                  Statistics Canada       NaN        NaN
169                                                and       NaN        NaN
170             Demographic Analysis Section, BC Stats       NaN        NaN
171                     Ministry of Citizens’ Services       NaN        NaN
172                     Government of British Columbia       NaN        NaN
173                                                NaN       NaN        NaN
174                                          May, 2024       NaN        NaN
175                                                NaN       NaN        NaN
176                                             Notes:       NaN        NaN
177  RD = Regional District, R = Region, RDR = Regi...       NaN        NaN
178  CY = City, T = Town, VL = Village, DM = Distri...       NaN        NaN
179         SGC = Standard Geographical Classification       NaN        NaN
180  Metro Vancouver Regional District (15000) was ...       NaN        NaN
181  Qathet Regional District (27000) was formerly ...       NaN        NaN
182  North Coast Regional District (47000) was form...       NaN        NaN
183  Jumbo Glacier Mountain Resort Municipality has...       NaN        NaN
184  All figures correspond to municipal boundaries...       NaN        NaN
185  All figures are as of July 1st of the year sta...       NaN        NaN

          2002       2003       2004       2005       2006       2007  \
156    25856.0    26328.0    26842.0    27319.0    28007.0    28681.0
157    42795.0    42815.0    42812.0    42904.0    43023.0    43209.0
158     9441.0     9525.0     9567.0     9521.0     9721.0     9175.0
159    18917.0    18963.0    18997.0    19071.0    19181.0    19045.0
160    11400.0    11215.0    11076.0    11002.0    11084.0    11206.0
161      220.0      214.0      207.0      204.0      192.0      181.0
162  3621136.0  3643685.0  3671958.0  3708935.0  3751262.0  3798364.0
163   479368.0   480762.0   483672.0   487141.0   490531.0   492623.0
164  4100504.0  4124447.0  4155630.0  4196076.0  4241793.0  4290987.0
165        NaN        NaN        NaN        NaN        NaN        NaN
166        NaN        NaN        NaN        NaN        NaN        NaN
167        NaN        NaN        NaN        NaN        NaN        NaN
168        NaN        NaN        NaN        NaN        NaN        NaN
169        NaN        NaN        NaN        NaN        NaN        NaN
170        NaN        NaN        NaN        NaN        NaN        NaN
171        NaN        NaN        NaN        NaN        NaN        NaN
172        NaN        NaN        NaN        NaN        NaN        NaN
173        NaN        NaN        NaN        NaN        NaN        NaN
174        NaN        NaN        NaN        NaN        NaN        NaN
175        NaN        NaN        NaN        NaN        NaN        NaN
176        NaN        NaN        NaN        NaN        NaN        NaN
177        NaN        NaN        NaN        NaN        NaN        NaN
178        NaN        NaN        NaN        NaN        NaN        NaN
179        NaN        NaN        NaN        NaN        NaN        NaN
180        NaN        NaN        NaN        NaN        NaN        NaN
181        NaN        NaN        NaN        NaN        NaN        NaN
182        NaN        NaN        NaN        NaN        NaN        NaN
183        NaN        NaN        NaN        NaN        NaN        NaN
184        NaN        NaN        NaN        NaN        NaN        NaN
185        NaN        NaN        NaN        NaN        NaN        NaN

          2008  ...  2001-02 Changes  2002-03 Changes  2003-04 Changes  \
156    29679.0  ...            0.015            0.018            0.020
157    42770.0  ...            0.002            0.000            0.000
158     9594.0  ...            0.004            0.009            0.004
159    19098.0  ...            0.004            0.002            0.002
160    11284.0  ...           -0.022           -0.016           -0.012
161      169.0  ...           -0.048           -0.027           -0.033
162  3855162.0  ...            0.007            0.006            0.008
163   494176.0  ...           -0.002            0.003            0.006
164  4349338.0  ...            0.006            0.006            0.008
165        NaN  ...              NaN              NaN              NaN
166        NaN  ...              NaN              NaN              NaN
167        NaN  ...              NaN              NaN              NaN
168        NaN  ...              NaN              NaN              NaN
169        NaN  ...              NaN              NaN              NaN
170        NaN  ...              NaN              NaN              NaN
171        NaN  ...              NaN              NaN              NaN
172        NaN  ...              NaN              NaN              NaN
173        NaN  ...              NaN              NaN              NaN
174        NaN  ...              NaN              NaN              NaN
175        NaN  ...              NaN              NaN              NaN
176        NaN  ...              NaN              NaN              NaN
177        NaN  ...              NaN              NaN              NaN
178        NaN  ...              NaN              NaN              NaN
179        NaN  ...              NaN              NaN              NaN
180        NaN  ...              NaN              NaN              NaN
181        NaN  ...              NaN              NaN              NaN
182        NaN  ...              NaN              NaN              NaN
183        NaN  ...              NaN              NaN              NaN
184        NaN  ...              NaN              NaN              NaN
185        NaN  ...              NaN              NaN              NaN

     2004-05 Changes  2005-06 Changes  2006-07 Changes  2007-08 Changes  \
156            0.018            0.025            0.024            0.035
157            0.002            0.003            0.004           -0.010
158           -0.005            0.021           -0.056            0.046
159            0.004            0.006           -0.007            0.003
160           -0.007            0.007            0.011            0.007
161           -0.014           -0.059           -0.057           -0.066
162            0.010            0.011            0.013            0.015
163            0.007            0.007            0.004            0.003
164            0.010            0.011            0.012            0.014
165              NaN              NaN              NaN              NaN
166              NaN              NaN              NaN              NaN
167              NaN              NaN              NaN              NaN
168              NaN              NaN              NaN              NaN
169              NaN              NaN              NaN              NaN
170              NaN              NaN              NaN              NaN
171              NaN              NaN              NaN              NaN
172              NaN              NaN              NaN              NaN
173              NaN              NaN              NaN              NaN
174              NaN              NaN              NaN              NaN
175              NaN              NaN              NaN              NaN
176              NaN              NaN              NaN              NaN
177              NaN              NaN              NaN              NaN
178              NaN              NaN              NaN              NaN
179              NaN              NaN              NaN              NaN
180              NaN              NaN              NaN              NaN
181              NaN              NaN              NaN              NaN
182              NaN              NaN              NaN              NaN
183              NaN              NaN              NaN              NaN
184              NaN              NaN              NaN              NaN
185              NaN              NaN              NaN              NaN

     2008-09 Changes  2009-10 Changes  2010-11 Changes
156            0.029            0.021            0.009
157            0.007            0.008           -0.004
158            0.057            0.015           -0.007
159            0.018            0.016           -0.011

In [195]:
#Validate Tail is removed
print(df_pop_2011_2024.tail(10))
print(df_pop_2001_2011.tail(10))

               Name Area Type     2011     2012     2013     2014     2015  \
151          Vernon        CY  38813.0  39278.0  39500.0  40226.0  40813.0
152        Victoria        CY  82464.0  83422.0  85139.0  86573.0  88248.0
153      View Royal         T   9582.0   9871.0  10056.0  10577.0  10663.0
154        Warfield        VL   1729.0   1663.0   1662.0   1695.0   1694.0
155           Wells        DM    247.0    241.0    237.0    233.0    228.0
156    West Kelowna        CY  31466.0  31791.0  32347.0  32776.0  33357.0
157  West Vancouver        DM  43238.0  43418.0  43652.0  43799.0  43769.0
158        Whistler        DM  10232.0  10542.0  10887.0  11457.0  11810.0
159      White Rock        CY  19544.0  19705.0  19761.0  20143.0  20297.0
160   Williams Lake        CY  11027.0  11100.0  11119.0  11257.0  11236.0

        2016     2017     2018  ...  2014-15 Changes  2015-16 Changes  \
151  41677.0  42470.0  43203.0  ...            0.015            0.021
152  90236.0  91802.0  93668.0  ...            0.019            0.023
153  10870.0  11185.0  11327.0  ...            0.008            0.019
154   1749.0   1743.0   1745.0  ...           -0.001            0.032
155    227.0    227.0    228.0  ...           -0.021           -0.004
156  34040.0  34697.0  35404.0  ...            0.018            0.020
157  43889.0  43957.0  44162.0  ...           -0.001            0.003
158  12622.0  13322.0  13999.0  ...            0.031            0.069
159  20643.0  21117.0  21638.0  ...            0.008            0.017
160  11176.0  11141.0  11284.0  ...           -0.002           -0.005

     2016-17 Changes  2017-18 Changes  2018-19 Changes  2019-20 Changes  \
151            0.019            0.017            0.025            0.024
152            0.017            0.020            0.023            0.006
153            0.029            0.013            0.025            0.024
154           -0.003            0.001           -0.006            0.018
155            0.000            0.004            0.000           -0.004
156            0.019            0.020            0.016            0.023
157            0.002            0.005            0.011            0.011
158            0.055            0.051            0.066            0.035
159            0.023            0.025            0.015            0.013
160           -0.003            0.013            0.009           -0.005

     2020-21 Changes  2021-22 Changes  2022-23 Changes  2023-24 Changes
151            0.019            0.022            0.017            0.024
152           -0.001            0.021            0.023            0.023
153            0.015            0.033            0.005            0.008
154            0.037           -0.001           -0.032           -0.003
155            0.000            0.009            0.004            0.004
156            0.021            0.035            0.024            0.007
157            0.009            0.019            0.026            0.026
158           -0.044            0.023            0.063           -0.027
159            0.015            0.041            0.046            0.022
160            0.010           -0.013            0.008           -0.001

[10 rows x 29 columns]
               Name Area Type     2001     2002     2003     2004     2005  \
151          Vernon        CY  35059.0  35229.0  35587.0  36026.0  36634.0
152        Victoria        CY  77863.0  78295.0  78725.0  79198.0  79912.0
153      View Royal         T   7617.0   7860.0   8106.0   8372.0   8675.0
154        Warfield        VL   1813.0   1789.0   1770.0   1754.0   1764.0
155           Wells        DM    244.0    241.0    237.0    237.0    240.0
156    West Kelowna        CY  25477.0  25856.0  26328.0  26842.0  27319.0
157  West Vancouver        DM  42691.0  42795.0  42815.0  42812.0  42904.0
158        Whistler        DM   9405.0   9441.0   9525.0   9567.0   9521.0
159      White Rock        CY  18844.0  18917.0  18963.0  18997.0  19071.0
160   Williams Lake        CY  11660.0  11400.0  11215.0  11076.0  11002.0

        2006     2007     2008  ...  2001-02 Changes  2002-03 Changes  \
151  36950.0  37433.0  38094.0  ...            0.005            0.010
152  80892.0  80957.0  81293.0  ...            0.006            0.005
153   9026.0   9032.0   9227.0  ...            0.032            0.031
154   1762.0   1771.0   1766.0  ...           -0.013           -0.011
155    243.0    246.0    247.0  ...           -0.012           -0.017
156  28007.0  28681.0  29679.0  ...            0.015            0.018
157  43023.0  43209.0  42770.0  ...            0.002            0.000
158   9721.0   9175.0   9594.0  ...            0.004            0.009
159  19181.0  19045.0  19098.0  ...            0.004            0.002
160  11084.0  11206.0  11284.0  ...           -0.022           -0.016

     2003-04 Changes  2004-05 Changes  2005-06 Changes  2006-07 Changes  \
151            0.012            0.017            0.009            0.013
152            0.006            0.009            0.012            0.001
153            0.033            0.036            0.040            0.001
154           -0.009            0.006           -0.001            0.005
155            0.000            0.013            0.013            0.012
156            0.020            0.018            0.025            0.024
157            0.000            0.002            0.003            0.004
158            0.004           -0.005            0.021           -0.056
159            0.002            0.004            0.006           -0.007
160           -0.012           -0.007            0.007            0.011

     2007-08 Changes  2008-09 Changes  2009-10 Changes  2010-11 Changes
151            0.018            0.011            0.006            0.001
152            0.004            0.008            0.005            0.001
153            0.022            0.013            0.013            0.012
154           -0.003           -0.015           -0.007            0.001
155            0.004            0.004           -0.004            0.000
156            0.035            0.029            0.021            0.009
157           -0.010            0.007            0.008           -0.004
158            0.046            0.057            0.015           -0.007
159            0.003            0.018            0.016           -0.011
160            0.007           -0.012           -0.009           -0.002

[10 rows x 23 columns]

In [196]:
#Check the data in 2011 column with is common in both the dataframes
Compare2011toEliminateDup = (df_pop_2001_2011['2011'] == df_pop_2011_2024['2011']).all()
print(f"Are the 2011 population columns in both dataframes identical? {Compare2011toEliminateDup}")

Are the 2011 population columns in both dataframes identical? True

In [197]:
df_pop_2011_2024 = df_pop_2011_2024.drop(columns=['2011'])
df_pop_2011_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             161 non-null    object
 1   Area Type        161 non-null    object
 2   2012             161 non-null    float64
 3   2013             161 non-null    float64
 4   2014             161 non-null    float64
 5   2015             161 non-null    float64
 6   2016             161 non-null    float64
 7   2017             161 non-null    float64
 8   2018             161 non-null    float64
 9   2019             161 non-null    float64
 10  2020             161 non-null    float64
 11  2021             161 non-null    float64
 12  2022             161 non-null    float64
 13  2023             161 non-null    float64
 14  2024             161 non-null    float64
 15  2011-12 Changes  161 non-null    float64
 16  2012-13 Changes  161 non-null    float64
 17  2013-14 Changes  161 non-null    float64
 18  2014-15 Changes  161 non-null    float64
 19  2015-16 Changes  161 non-null    float64
 20  2016-17 Changes  161 non-null    float64
 21  2017-18 Changes  161 non-null    float64
 22  2018-19 Changes  161 non-null    float64
 23  2019-20 Changes  161 non-null    float64
 24  2020-21 Changes  161 non-null    float64
 25  2021-22 Changes  161 non-null    float64
 26  2022-23 Changes  161 non-null    float64
 27  2023-24 Changes  161 non-null    float64
dtypes: float64(26), object(2)
memory usage: 35.3+ KB

In [199]:
print(df_pop_2001_2011.columns)
print(df_pop_2011_2024.columns)

Index(['Name', 'Area Type', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2001-02 Changes',
       '2002-03 Changes', '2003-04 Changes', '2004-05 Changes',
       '2005-06 Changes', '2006-07 Changes', '2007-08 Changes',
       '2008-09 Changes', '2009-10 Changes', '2010-11 Changes'],
      dtype='object')
Index(['Name', 'Area Type', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020', '2021', '2022', '2023', '2024',
       '2011-12 Changes', '2012-13 Changes', '2013-14 Changes',
       '2014-15 Changes', '2015-16 Changes', '2016-17 Changes',
       '2017-18 Changes', '2018-19 Changes', '2019-20 Changes',
       '2020-21 Changes', '2021-22 Changes', '2022-23 Changes',
       '2023-24 Changes'],
      dtype='object')

In [200]:
unique_city_11 = df_pop_2001_2011['Name'].unique()
unique_city_24 = df_pop_2011_2024['Name'].unique()
#Print the cities present in 2001-2011 data but not in 2011 - 2024 data
cities_not_in_11 = set(unique_city_11) - set(unique_city_24)
cities_not_in_24 = set(unique_city_24) - set(unique_city_11)

print(cities_not_in_24)

{'shíshálh Nation Gov Dist (Part-qathet)', 'shíshálh Nation Gov Dist (Part-Sunshine Coast)', 'Sechelt, District Municipality'}

In [202]:
#update the City names in df_pop_2011_2024 to match with df_pop_2001_2011
df_pop_2011_2024['Name'] = df_pop_2011_2024['Name'].replace({
    'Sechelt, District Municipality': 'Sechelt District Municipality',
    'shíshálh Nation Gov Dist (Part-Sunshine Coast)': 'Sechelt Ind Gov Dist (Part-Sunshine Coast)',
    'shíshálh Nation Gov Dist (Part-qathet)': 'Sechelt Ind Gov Dist (Part-qathet)'
})

In [208]:
#Combine both the dataframes based on Name column
df_Comb_pop = pd.merge(df_pop_2001_2011, df_pop_2011_2024, on='Name', how='inner')

In [209]:
df_Comb_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 50 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             161 non-null    object
 1   Area Type_x      161 non-null    object
 2   2001             161 non-null    float64
 3   2002             161 non-null    float64
 4   2003             161 non-null    float64
 5   2004             161 non-null    float64
 6   2005             161 non-null    float64
 7   2006             161 non-null    float64
 8   2007             161 non-null    float64
 9   2008             161 non-null    float64
 10  2009             161 non-null    float64
 11  2010             161 non-null    float64
 12  2011             161 non-null    float64
 13  2001-02 Changes  161 non-null    float64
 14  2002-03 Changes  161 non-null    float64
 15  2003-04 Changes  161 non-null    float64
 16  2004-05 Changes  161 non-null    float64
 17  2005-06 Changes  161 non-null    float64
 18  2006-07 Changes  161 non-null    float64
 19  2007-08 Changes  161 non-null    float64
 20  2008-09 Changes  161 non-null    float64
 21  2009-10 Changes  161 non-null    float64
 22  2010-11 Changes  161 non-null    float64
 23  Area Type_y      161 non-null    object
 24  2012             161 non-null    float64
 25  2013             161 non-null    float64
 26  2014             161 non-null    float64
 27  2015             161 non-null    float64
 28  2016             161 non-null    float64
 29  2017             161 non-null    float64
 30  2018             161 non-null    float64
 31  2019             161 non-null    float64
 32  2020             161 non-null    float64
 33  2021             161 non-null    float64
 34  2022             161 non-null    float64
 35  2023             161 non-null    float64
 36  2024             161 non-null    float64
 37  2011-12 Changes  161 non-null    float64
 38  2012-13 Changes  161 non-null    float64
 39  2013-14 Changes  161 non-null    float64
 40  2014-15 Changes  161 non-null    float64
 41  2015-16 Changes  161 non-null    float64
 42  2016-17 Changes  161 non-null    float64
 43  2017-18 Changes  161 non-null    float64
 44  2018-19 Changes  161 non-null    float64
 45  2019-20 Changes  161 non-null    float64
 46  2020-21 Changes  161 non-null    float64
 47  2021-22 Changes  161 non-null    float64
 48  2022-23 Changes  161 non-null    float64
 49  2023-24 Changes  161 non-null    float64
dtypes: float64(47), object(3)
memory usage: 63.0+ KB

In [210]:
print(df_Comb_pop.columns)

Index(['Name', 'Area Type_x', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2001-02 Changes',
       '2002-03 Changes', '2003-04 Changes', '2004-05 Changes',
       '2005-06 Changes', '2006-07 Changes', '2007-08 Changes',
       '2008-09 Changes', '2009-10 Changes', '2010-11 Changes', 'Area Type_y',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', '2024', '2011-12 Changes', '2012-13 Changes',
       '2013-14 Changes', '2014-15 Changes', '2015-16 Changes',
       '2016-17 Changes', '2017-18 Changes', '2018-19 Changes',
       '2019-20 Changes', '2020-21 Changes', '2021-22 Changes',
       '2022-23 Changes', '2023-24 Changes'],
      dtype='object')

In [211]:
df_Comb_pop = df_Comb_pop.drop(columns=['Area Type_y'])

In [212]:
df_Comb_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 49 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             161 non-null    object
 1   Area Type_x      161 non-null    object
 2   2001             161 non-null    float64
 3   2002             161 non-null    float64
 4   2003             161 non-null    float64
 5   2004             161 non-null    float64
 6   2005             161 non-null    float64
 7   2006             161 non-null    float64
 8   2007             161 non-null    float64
 9   2008             161 non-null    float64
 10  2009             161 non-null    float64
 11  2010             161 non-null    float64
 12  2011             161 non-null    float64
 13  2001-02 Changes  161 non-null    float64
 14  2002-03 Changes  161 non-null    float64
 15  2003-04 Changes  161 non-null    float64
 16  2004-05 Changes  161 non-null    float64
 17  2005-06 Changes  161 non-null    float64
 18  2006-07 Changes  161 non-null    float64
 19  2007-08 Changes  161 non-null    float64
 20  2008-09 Changes  161 non-null    float64
 21  2009-10 Changes  161 non-null    float64
 22  2010-11 Changes  161 non-null    float64
 23  2012             161 non-null    float64
 24  2013             161 non-null    float64
 25  2014             161 non-null    float64
 26  2015             161 non-null    float64
 27  2016             161 non-null    float64
 28  2017             161 non-null    float64
 29  2018             161 non-null    float64
 30  2019             161 non-null    float64
 31  2020             161 non-null    float64
 32  2021             161 non-null    float64
 33  2022             161 non-null    float64
 34  2023             161 non-null    float64
 35  2024             161 non-null    float64
 36  2011-12 Changes  161 non-null    float64
 37  2012-13 Changes  161 non-null    float64
 38  2013-14 Changes  161 non-null    float64
 39  2014-15 Changes  161 non-null    float64
 40  2015-16 Changes  161 non-null    float64
 41  2016-17 Changes  161 non-null    float64
 42  2017-18 Changes  161 non-null    float64
 43  2018-19 Changes  161 non-null    float64
 44  2019-20 Changes  161 non-null    float64
 45  2020-21 Changes  161 non-null    float64
 46  2021-22 Changes  161 non-null    float64
 47  2022-23 Changes  161 non-null    float64
 48  2023-24 Changes  161 non-null    float64
dtypes: float64(47), object(2)
memory usage: 61.8+ KB

In [213]:
# Identifying the columns with "Changes" in their names
Cols_with_change = [col for col in df_Comb_pop.columns if 'Change' in col]
# Dropping the identified columns
df_Comb_pop = df_Comb_pop.drop(columns=Cols_with_change)
#verify they are dropped
print(df_Comb_pop.columns)

Index(['Name', 'Area Type_x', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024'],
      dtype='object')

In [214]:
#Create a mapping dictionary for Area Type codes to descriptive names and update the Area Type column
area_type_map = { 
    'CY' : 'City', 
    'T' : 'Town',
    'VL' : 'Village',
    'DM' : 'District Municipality', 
    'IM' : 'Island Municipality',
    'RGM' : 'Regional Municipality'}
df_Comb_pop['Area Type_x'] = df_Comb_pop['Area Type_x'].map(area_type_map)
df_Comb_pop = df_Comb_pop.rename(columns={'Area Type_x': 'Area Type'})
df_Comb_pop.head()

,Name,Area Type,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abbotsford,City,121125.0,122136.0,123356.0,125348.0,126944.0,128379.0,129859.0,131615.0,...,144475.0,148121.0,150566.0,153940.0,157306.0,159139.0,160759.0,164237.0,169440.0,175087.0
1,Alert Bay,Village,584.0,531.0,491.0,464.0,422.0,376.0,387.0,401.0,...,478.0,489.0,463.0,441.0,439.0,424.0,464.0,495.0,503.0,499.0
2,Anmore,Village,1406.0,1487.0,1567.0,1654.0,1746.0,1855.0,1962.0,2049.0,...,2292.0,2316.0,2430.0,2419.0,2453.0,2452.0,2456.0,2526.0,2548.0,2568.0
3,Armstrong,City,4445.0,4411.0,4387.0,4385.0,4388.0,4369.0,4529.0,4670.0,...,5182.0,5300.0,5235.0,5413.0,5446.0,5422.0,5499.0,5636.0,5727.0,5767.0
4,Ashcroft,Village,1871.0,1824.0,1774.0,1738.0,1711.0,1686.0,1674.0,1707.0,...,1544.0,1608.0,1697.0,1631.0,1639.0,1686.0,1705.0,1804.0,1768.0,1737.0

In [149]:
df_Comb_pop.head()

,Name,Area Type,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abbotsford,City,121125.0,122136.0,123356.0,125348.0,126944.0,128379.0,129859.0,131615.0,...,144475.0,148121.0,150566.0,153940.0,157306.0,159139.0,160759.0,164237.0,169440.0,175087.0
1,Alert Bay,Village,584.0,531.0,491.0,464.0,422.0,376.0,387.0,401.0,...,478.0,489.0,463.0,441.0,439.0,424.0,464.0,495.0,503.0,499.0
2,Anmore,Village,1406.0,1487.0,1567.0,1654.0,1746.0,1855.0,1962.0,2049.0,...,2292.0,2316.0,2430.0,2419.0,2453.0,2452.0,2456.0,2526.0,2548.0,2568.0
3,Armstrong,City,4445.0,4411.0,4387.0,4385.0,4388.0,4369.0,4529.0,4670.0,...,5182.0,5300.0,5235.0,5413.0,5446.0,5422.0,5499.0,5636.0,5727.0,5767.0
4,Ashcroft,Village,1871.0,1824.0,1774.0,1738.0,1711.0,1686.0,1674.0,1707.0,...,1544.0,1608.0,1697.0,1631.0,1639.0,1686.0,1705.0,1804.0,1768.0,1737.0

In [150]:
swt_file_path = "../00_data/2023_2024-annual-surgical_wait_times.xlsx"
# Read the population data from Excel file and sheet "Mun Name Sort"
df_surgical_waitTime_2009_2024 = pd.read_excel(swt_file_path)

In [151]:
df_surgical_waitTime_2009_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51528 entries, 0 to 51527
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   FISCAL_YEAR                51528 non-null  object
 1   HEALTH_AUTHORITY           51528 non-null  object
 2   HOSPITAL_NAME              51528 non-null  object
 3   PROCEDURE_GROUP            51528 non-null  object
 4   WAITING                    51528 non-null  object
 5   COMPLETED                  51528 non-null  object
 6   COMPLETED_50TH_PERCENTILE  41298 non-null  float64
 7   COMPLETED_90TH_PERCENTILE  41298 non-null  float64
dtypes: float64(2), object(6)
memory usage: 3.1+ MB

In [152]:
df_surgical_waitTime_2009_2024 = df_surgical_waitTime_2009_2024.fillna(0)

In [153]:
df_surgical_waitTime_2009_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51528 entries, 0 to 51527
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   FISCAL_YEAR                51528 non-null  object
 1   HEALTH_AUTHORITY           51528 non-null  object
 2   HOSPITAL_NAME              51528 non-null  object
 3   PROCEDURE_GROUP            51528 non-null  object
 4   WAITING                    51528 non-null  object
 5   COMPLETED                  51528 non-null  object
 6   COMPLETED_50TH_PERCENTILE  51528 non-null  float64
 7   COMPLETED_90TH_PERCENTILE  51528 non-null  float64
dtypes: float64(2), object(6)
memory usage: 3.1+ MB

In [154]:
df_surgical_waitTime_2009_2024.head()

,FISCAL_YEAR,HEALTH_AUTHORITY,HOSPITAL_NAME,PROCEDURE_GROUP,WAITING,COMPLETED,COMPLETED_50TH_PERCENTILE,COMPLETED_90TH_PERCENTILE
0,2009/10,All Health Authorities,All Facilities,Abdominoplasty,52,100,9.1,42.6
1,2009/10,All Health Authorities,All Facilities,All Other Procedures,1378,6287,4.0,17.1
2,2009/10,All Health Authorities,All Facilities,All Procedures,72133,219512,5.3,24.3
3,2009/10,All Health Authorities,All Facilities,Aortic Aneurysm Repair,96,365,3.7,13.5
4,2009/10,All Health Authorities,All Facilities,Appendectomy,19,88,3.7,9.1

In [216]:
#create a function to map fiscal year to calendar year
def map_fiscal_to_year(fiscal):
    return int(fiscal.split('/')[0]) + 1  # 2009/10 → 2010
#Create a new column 'Calendar_Year' by applying the mapping function
df_surgical_waitTime_2009_2024['Calendar_Year'] = df_surgical_waitTime_2009_2024['FISCAL_YEAR'].apply(map_fiscal_to_year)
df_surgical_waitTime_2009_2024[['Calendar_Year','FISCAL_YEAR']].head()

   Calendar_Year FISCAL_YEAR
0           2010     2009/10
1           2010     2009/10
2           2010     2009/10
3           2010     2009/10
4           2010     2009/10

In [156]:
#Get Unique Health Authority Names to correlate with Population Data
print(df_surgical_waitTime_2009_2024['HEALTH_AUTHORITY'].unique())

['All Health Authorities' 'Fraser' 'Interior' 'Northern'
 'Provincial Health Services Authority' 'Vancouver Coastal'
 'Vancouver Island']

In [157]:
#Get Unique Hospital Names to correlate with Population Data
print(df_surgical_waitTime_2009_2024['HOSPITAL_NAME'].unique())
count_ha = df_surgical_waitTime_2009_2024['HOSPITAL_NAME'].nunique()
print(f"Total Unique Hospitals in the Data: {count_ha}")

['All Facilities' 'Abbotsford Regional Hospital And Cancer Centre'
 'Burnaby Hospital' 'Chilliwack General Hospital' 'Delta Hospital'
 'Eagle Ridge Hospital' 'Langley Memorial Hospital'
 'Pattison Outpatient Centre' 'Peace Arch Hospital'
 'Ridge Meadows Hospital' 'Royal Columbian Hospital'
 'Surrey Memorial Hospital' '100 Mile District General Hospital'
 'Cariboo Memorial Hospital' 'Creston Valley Hospital'
 'East Kootenay Regional Hospital' 'Elk Valley Hospital'
 'Golden And District General Hospital' 'Kelowna General Hospital'
 'Kootenay Boundary Regional Hospital' 'Kootenay Lake Hospital'
 'Lillooet Hospital And Health Centre' 'Penticton Regional Hospital'
 'Pleasant Valley Health Centre' 'Queen Victoria Hospital'
 'Royal Inland Hospital' 'Shuswap Lake General Hospital'
 'Summerland Memorial Health Centre' 'Vernon Jubilee Hospital'
 'Bulkley Valley District Hospital' 'Dawson Creek And District Hospital'
 'Fort St John General Hospital' 'G.R. Baker Memorial Hospital'
 'Kitimat General Hospital' 'Mills Memorial Hospital'
 'Prince Rupert Regional Hospital' 'St. John Hospital'
 'The University Hospital Of Northern British Columbia'
 'Wrinch Memorial Hospital' 'B.C. Cancer Agency'
 "B.C. Children'S Hospital" "B.C. Women'S Hospital" 'Lions Gate Hospital'
 'Mount Saint Joseph Hospital' 'Powell River General Hospital'
 'Richmond Hospital' 'Sechelt Hospital' 'Squamish General Hospital'
 "St. Paul'S Hospital" 'Ubc Health Sciences Centre'
 'Vancouver General Hospital'
 'Campbell River And District General Hospital'
 'Cowichan District Hospital' 'Nanaimo Regional General Hospital'
 'Royal Jubilee Hospital' 'Saanich Peninsula Hospital'
 "St. Joseph'S General Hospital" 'Victoria General Hospital'
 'West Coast General Hospital' 'Comox Valley Hospital'
 'South Island Surgical Centre' 'Centre Island Surgical Centre'
 'Surgery Centre' 'Qathet General Hospital' 'Fort Nelson General Hospital'
 'Lakes District Hospital And Health Centre' 'Mission Memorial Hospital']
Total Unique Hospitals in the Data: 67

In [ ]:
#Found the Hospital Locations in BC to map with Population Data using Gemini LLM.
hospital_locations_bc = {
    'Abbotsford Regional Hospital And Cancer Centre': 'Abbotsford',
    'Burnaby Hospital': 'Burnaby',
    'Chilliwack General Hospital': 'Chilliwack',
    'Delta Hospital': 'Delta',
    'Eagle Ridge Hospital': 'Port Moody',
    'Langley Memorial Hospital': 'Langley', 
    'Pattison Outpatient Centre': 'Surrey', 
    'Peace Arch Hospital': 'White Rock', 
    'Ridge Meadows Hospital': 'Maple Ridge', 
    'Royal Columbian Hospital': 'New Westminster', 
    'Surrey Memorial Hospital': 'Surrey',
    '100 Mile District General Hospital': '100 Mile House',
    'Cariboo Memorial Hospital': 'Williams Lake',
    'Creston Valley Hospital': 'Creston',
    'East Kootenay Regional Hospital': 'Cranbrook',
    'Elk Valley Hospital': 'Fernie',
    'Golden And District General Hospital': 'Golden', 
    'Kelowna General Hospital': 'Kelowna', # Based on name and common knowledge
    'Kootenay Boundary Regional Hospital': 'Trail', # Commonly known location
    'Kootenay Lake Hospital': 'Nelson', # Commonly known location
    'Lillooet Hospital And Health Centre': 'Lillooet',
    'Penticton Regional Hospital': 'Penticton', # Based on name and common knowledge
    'Pleasant Valley Health Centre': 'Armstrong', # Commonly known location
    'Queen Victoria Hospital': 'Revelstoke', # Commonly known location
    'Royal Inland Hospital': 'Kamloops', # Commonly known location
    'Shuswap Lake General Hospital': 'Salmon Arm', # Commonly known location
    'Summerland Memorial Health Centre': 'Summerland', # Based on name and common knowledge
    'Vernon Jubilee Hospital': 'Vernon', # Based on name and common knowledge
    'Bulkley Valley District Hospital': 'Smithers',
    'Dawson Creek And District Hospital': 'Dawson Creek',
    'Fort St John General Hospital': 'Fort St. John', # Based on name and common knowledge
    'G.R. Baker Memorial Hospital': 'Quesnel', # Commonly known location
    'Kitimat General Hospital': 'Kitimat', # Based on name and common knowledge
    'Mills Memorial Hospital': 'Terrace', # Commonly known location
    'Prince Rupert Regional Hospital': 'Prince Rupert', # Based on name and common knowledge
    'St. John Hospital': 'Vanderhoof', # Commonly known location
    'The University Hospital Of Northern British Columbia': 'Prince George', # Commonly known location
    'Wrinch Memorial Hospital': 'Hazelton', # Commonly known location
    'B.C. Cancer Agency': 'Vancouver', # Main site at 600 W 10th Ave
    "B.C. Children'S Hospital": 'Vancouver',
    "B.C. Women'S Hospital": 'Vancouver',
    'Lions Gate Hospital': 'North Vancouver', # Commonly known location
    'Mount Saint Joseph Hospital': 'Vancouver', # Commonly known location
    'Powell River General Hospital': 'Powell River',
    'Richmond Hospital': 'Richmond', # Based on name and common knowledge
    'Sechelt Hospital': 'Sechelt', # Based on name and common knowledge
    'Squamish General Hospital': 'Squamish', # Based on name and common knowledge
    "St. Paul'S Hospital": 'Vancouver', # Commonly known location
    'Ubc Health Sciences Centre': 'Vancouver', # Located on UBC Campus
    'Vancouver General Hospital': 'Vancouver',
    'Campbell River And District General Hospital': 'Campbell River',
    'Cowichan District Hospital': 'Duncan',
    'Nanaimo Regional General Hospital': 'Nanaimo', # Commonly known location
    'Royal Jubilee Hospital': 'Victoria', # Commonly known location
    'Saanich Peninsula Hospital': 'Central Saanich', # Commonly known location
    "St. Joseph'S General Hospital": 'Comox', # Commonly known location
    'Victoria General Hospital': 'Victoria', # Commonly known location
    'West Coast General Hospital': 'Port Alberni', # Commonly known location
    'Comox Valley Hospital': 'Courtenay',
    'South Island Surgical Centre': 'Victoria', # Commonly known location
    'Centre Island Surgical Centre': 'Nanaimo',
    'Surgery Centre': 'Vancouver', # Refers to VGH/St. Paul's or another major center
    'Qathet General Hospital': 'Powell River',
    'Fort Nelson General Hospital': 'Fort Nelson',
    'Lakes District Hospital And Health Centre': 'Burns Lake', # Commonly known location
    'Mission Memorial Hospital': 'Mission' # Commonly known location
}

In [218]:
#Mapping the Hospital Names to their respective Cities
df_surgical_waitTime_2009_2024['City'] = df_surgical_waitTime_2009_2024['HOSPITAL_NAME'].map(hospital_locations_bc)

In [160]:
df_surgical_waitTime_2009_2024['WAITING_INT'] = (
    df_surgical_waitTime_2009_2024['WAITING']
    .astype(str) # Ensure it's treated as a string for replacement
    .str.replace('<', '', regex=False)
)
df_surgical_waitTime_2009_2024['WAITING_INT'] = pd.to_numeric(
    df_surgical_waitTime_2009_2024['WAITING_INT'], 
    errors='coerce'
)

df_surgical_waitTime_2009_2024['COMPLETED_INT'] = (
    df_surgical_waitTime_2009_2024['COMPLETED']
    .astype(str) # Ensure it's treated as a string for replacement
    .str.replace('<', '', regex=False)
)
df_surgical_waitTime_2009_2024['COMPLETED_INT'] = pd.to_numeric(
    df_surgical_waitTime_2009_2024['COMPLETED_INT'], 
    errors='coerce'
)
df_surgical_waitTime_2009_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51528 entries, 0 to 51527
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   FISCAL_YEAR                51528 non-null  object
 1   HEALTH_AUTHORITY           51528 non-null  object
 2   HOSPITAL_NAME              51528 non-null  object
 3   PROCEDURE_GROUP            51528 non-null  object
 4   WAITING                    51528 non-null  object
 5   COMPLETED                  51528 non-null  object
 6   COMPLETED_50TH_PERCENTILE  51528 non-null  float64
 7   COMPLETED_90TH_PERCENTILE  51528 non-null  float64
 8   Calendar_Year              51528 non-null  int64
 9   City                       43094 non-null  object
 10  WAITING_INT                51528 non-null  int64
 11  COMPLETED_INT              51528 non-null  int64
dtypes: float64(2), int64(3), object(7)
memory usage: 4.7+ MB

In [161]:
#Display the data beteween 100 to 200 rows in df_surgical_waitTime_2009_2024

df_surgical_waitTime_2009_2024.iloc[100:200]

,FISCAL_YEAR,HEALTH_AUTHORITY,HOSPITAL_NAME,PROCEDURE_GROUP,WAITING,COMPLETED,COMPLETED_50TH_PERCENTILE,COMPLETED_90TH_PERCENTILE,Calendar_Year,City,WAITING_INT,COMPLETED_INT
100,2009/10,Fraser,Abbotsford Regional Hospital And Cancer Centre,Endarterectomy,12,80,4.5,11.1,2010,Abbotsford,12,80
101,2009/10,Fraser,Abbotsford Regional Hospital And Cancer Centre,Examination Under Anaesthetic,8,12,5.2,11.8,2010,Abbotsford,8,12
102,2009/10,Fraser,Abbotsford Regional Hospital And Cancer Centre,Excision Gynecomastia,11,33,8.4,70.3,2010,Abbotsford,11,33
103,2009/10,Fraser,Abbotsford Regional Hospital And Cancer Centre,Excision Lesion/Tumour,18,60,5.6,25.0,2010,Abbotsford,18,60
104,2009/10,Fraser,Abbotsford Regional Hospital And Cancer Centre,Fallopian Tube/Ovarian Surgery,117,199,11.1,25.3,2010,Abbotsford,117,199
...,...,...,...,...,...,...,...,...,...,...,...,...
195,2009/10,Fraser,All Facilities,Lung Surgery,23,112,2.7,5.4,2010,NaN,23,112
196,2009/10,Fraser,All Facilities,Male Reproductive Surgery,258,637,3.9,23.6,2010,NaN,258,637
197,2009/10,Fraser,All Facilities,Mastectomy,75,814,2.0,6.1,2010,NaN,75,814
198,2009/10,Fraser,All Facilities,Mastoidectomy,24,38,9.1,17.9,2010,NaN,24,38
199,2009/10,Fraser,All Facilities,Myringotomy,134,466,4.4,12.6,2010,NaN,134,466

In [162]:
#Get the Fraser health authority details "All Facilities" and compare with the data with Facility name to ensure we can drop the rows.
mask_health_authority = (df_surgical_waitTime_2009_2024['HEALTH_AUTHORITY'] == 'Fraser')
mask_city_is_nan = (df_surgical_waitTime_2009_2024['City'].isnull())
mask_city_is_Notnan = (df_surgical_waitTime_2009_2024['City'].notnull())
filtered_data1 = df_surgical_waitTime_2009_2024[mask_health_authority & mask_city_is_nan]
filtered_data2 = df_surgical_waitTime_2009_2024[mask_health_authority & mask_city_is_Notnan]
filtered_data1['WAITING_INT'] = pd.to_numeric(filtered_data1['WAITING_INT'], errors='coerce')
filtered_data2['WAITING_INT'] = pd.to_numeric(filtered_data2['WAITING_INT'], errors='coerce')

sum_waiting_fraser_all = filtered_data1['WAITING_INT'].sum() 
sum_waiting_fraser = filtered_data2['WAITING_INT'].sum() 

print(f"Total WAITING for Fraser Health Authority 'All Facilities': {sum_waiting_fraser_all}")
print(f"Total WAITING for Fraser Health Authority with City Names: {sum_waiting_fraser}")

Total WAITING for Fraser Health Authority 'All Facilities': 711595
Total WAITING for Fraser Health Authority with City Names: 718875

C:\Users\Anushya E\AppData\Local\Temp\ipykernel_19100\4140462780.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data1['WAITING_INT'] = pd.to_numeric(filtered_data1['WAITING_INT'], errors='coerce')
C:\Users\Anushya E\AppData\Local\Temp\ipykernel_19100\4140462780.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data2['WAITING_INT'] = pd.to_numeric(filtered_data2['WAITING_INT'], errors='coerce')

In [163]:
# We see almost similar WAITING counts for Fraser Health Authority when comparing 'All Facilities' with the sum of individual hospitals.
# So dropping the 'All Facilities' rows for each Health Authority to avoid duplication in analysis.
df_surgical_waitTime_Cleaned = df_surgical_waitTime_2009_2024[df_surgical_waitTime_2009_2024['City'].notnull()]

In [164]:
#Drop the rows with 'All Health Authorities' in column HEALTH_AUTHORITY from df_surgical_waitTime_Cleaned
df_surgical_waitTime_Cleaned = df_surgical_waitTime_Cleaned[df_surgical_waitTime_Cleaned['HEALTH_AUTHORITY'] != 'All Health Authorities']

In [165]:
#Drop the columns FISCAL_YEAR, WAITING, COMPLETED from df_surgical_waitTime_Cleaned
columns_to_drop = ['FISCAL_YEAR', 'WAITING', 'COMPLETED']
df_surgical_waitTime_Cleaned = df_surgical_waitTime_Cleaned.drop(columns_to_drop, axis=1)
df_surgical_waitTime_Cleaned.head()

,HEALTH_AUTHORITY,HOSPITAL_NAME,PROCEDURE_GROUP,COMPLETED_50TH_PERCENTILE,COMPLETED_90TH_PERCENTILE,Calendar_Year,City,WAITING_INT,COMPLETED_INT
84,Fraser,Abbotsford Regional Hospital And Cancer Centre,Abdominoplasty,0.0,0.0,2010,Abbotsford,10,5
85,Fraser,Abbotsford Regional Hospital And Cancer Centre,All Other Procedures,4.0,34.2,2010,Abbotsford,30,59
86,Fraser,Abbotsford Regional Hospital And Cancer Centre,All Procedures,7.3,30.3,2010,Abbotsford,2376,5041
87,Fraser,Abbotsford Regional Hospital And Cancer Centre,Aortic Aneurysm Repair,5.1,12.1,2010,Abbotsford,18,14
88,Fraser,Abbotsford Regional Hospital And Cancer Centre,Appendectomy,0.0,0.0,2010,Abbotsford,5,5

In [166]:
#Display the cleaned surgical wait time data with reordered index. Just felt that would be better :) 
df_surgical_waitTime_Cleaned = df_surgical_waitTime_Cleaned.reset_index(drop=True)

In [167]:
df_surgical_waitTime_Cleaned.head()

,HEALTH_AUTHORITY,HOSPITAL_NAME,PROCEDURE_GROUP,COMPLETED_50TH_PERCENTILE,COMPLETED_90TH_PERCENTILE,Calendar_Year,City,WAITING_INT,COMPLETED_INT
0,Fraser,Abbotsford Regional Hospital And Cancer Centre,Abdominoplasty,0.0,0.0,2010,Abbotsford,10,5
1,Fraser,Abbotsford Regional Hospital And Cancer Centre,All Other Procedures,4.0,34.2,2010,Abbotsford,30,59
2,Fraser,Abbotsford Regional Hospital And Cancer Centre,All Procedures,7.3,30.3,2010,Abbotsford,2376,5041
3,Fraser,Abbotsford Regional Hospital And Cancer Centre,Aortic Aneurysm Repair,5.1,12.1,2010,Abbotsford,18,14
4,Fraser,Abbotsford Regional Hospital And Cancer Centre,Appendectomy,0.0,0.0,2010,Abbotsford,5,5

In [168]:
print(df_surgical_waitTime_Cleaned['PROCEDURE_GROUP'].unique())

['Abdominoplasty' 'All Other Procedures' 'All Procedures'
 'Aortic Aneurysm Repair' 'Appendectomy' 'Biopsy in OR' 'Bladder Surgery'
 'Bowel Resection' 'Breast Biopsy' 'Breast Reconstruction'
 'Breast Reduction' 'Cholecystectomy' 'Colostomy/Ileostomy'
 'Cyst/Ganglion Removal' 'D&C and Related Surgery' 'Dental Surgery'
 'Endarterectomy' 'Examination Under Anaesthetic' 'Excision Gynecomastia'
 'Excision Lesion/Tumour' 'Fallopian Tube/Ovarian Surgery'
 'Fistula Repair - Non Vascular' 'Foot/Ankle Surgery' 'Fracture Repair'
 'Hand/Wrist Surgery' 'Hernia Repair - Abdominal' 'Hernia Repair - Hiatal'
 'Hip Replacement' 'Kidney/Bladder Stone Removal' 'Knee - ACL Repair'
 'Knee - Meniscectomy' 'Knee Arthroscopy' 'Knee Replacement' 'Laparoscopy'
 'Lipectomy' 'Male Reproductive Surgery' 'Mastectomy' 'Myringotomy'
 'Nasal Surgery' 'Nerve Surgery' 'Oral Cavity & Pharynx Surgery'
 'Other Ear Surgery' 'Other Eye Surgery' 'Other Joint Reconstruction'
 'Other Orthopaedic Surgery' 'Other Urology Surgery' 'Parotidectomy'
 'Prostate Surgery' 'Rectal Surgery' 'Shoulder Surgery' 'Sinus Surgery'
 'Skin Surgery' 'Skin Tumour Removal' 'Sphincterotomy' 'Tendon Surgery'
 'Thyroidectomy' 'Tonsillectomy/Adenoidectomy' 'Tympanoplasty'
 'Uterine Surgery' 'Vaginal Repair' 'Varicose Veins Ligation/Stripping'
 'Vascular Bypass Graft - Non Cardiac' 'Vascular Surgery - Other'
 'Wound/Laceration Care' 'Cataract Surgery' 'Facial Bone Reconstruction'
 'Laparotomy' 'Lens & Vitreous (non-cataract) Surgery' 'Ligament Surgery'
 'Mastoidectomy' 'Spinal/Back Surgery' 'Cone Biopsy'
 'Foreign Body Removal Surgery' 'Bariatric Surgery' 'CSF Drainage'
 'Cranial Surgery' 'Lung Surgery' 'Shunt Insertion/Removal'
 'Esophagectomy' 'Free Flap Graft' 'Scope of Chest' 'Thoracotomy'
 'Rib Resection' 'Gastrostomy/Jejunostomy' 'Hernia Repair - Chest Wall']

In [169]:
#Drop the rows with 'All Procedures' in column PROCEDURE_GROUP from df_surgical_waitTime_Cleaned
df_surgical_waitTime_Cleaned = df_surgical_waitTime_Cleaned[df_surgical_waitTime_Cleaned['PROCEDURE_GROUP'] != 'All Procedures']

In [170]:
df_surgical_waitTime_Cleaned.head()

,HEALTH_AUTHORITY,HOSPITAL_NAME,PROCEDURE_GROUP,COMPLETED_50TH_PERCENTILE,COMPLETED_90TH_PERCENTILE,Calendar_Year,City,WAITING_INT,COMPLETED_INT
0,Fraser,Abbotsford Regional Hospital And Cancer Centre,Abdominoplasty,0.0,0.0,2010,Abbotsford,10,5
1,Fraser,Abbotsford Regional Hospital And Cancer Centre,All Other Procedures,4.0,34.2,2010,Abbotsford,30,59
3,Fraser,Abbotsford Regional Hospital And Cancer Centre,Aortic Aneurysm Repair,5.1,12.1,2010,Abbotsford,18,14
4,Fraser,Abbotsford Regional Hospital And Cancer Centre,Appendectomy,0.0,0.0,2010,Abbotsford,5,5
5,Fraser,Abbotsford Regional Hospital And Cancer Centre,Biopsy in OR,1.9,8.8,2010,Abbotsford,6,37

In [171]:
unique_city_surg = df_surgical_waitTime_Cleaned['City'].unique()
unique_city_pop = df_Comb_pop['Name'].unique()
#Print the cities present in surgical wait time data but not in population data
cities_not_in_pop = set(unique_city_surg) - set(unique_city_pop)
cities_not_in_surg = set(unique_city_pop) - set(unique_city_surg)

print(cities_not_in_pop)

{'100 Mile House', 'Langley', 'North Vancouver', 'Sechelt', 'Fort Nelson'}

In [172]:
#SELECT DATA FOR CITY NAME '100 Mile House'
df_surgical_waitTime_Cleaned[df_surgical_waitTime_Cleaned['City'] == '100 Mile House'].head()
# Use .replace() to substitute the old city name with the new, standardized name
df_surgical_waitTime_Cleaned['City'] = df_surgical_waitTime_Cleaned['City'].replace({
    '100 Mile House': 'One Hundred Mile House',
    'Sechelt': 'Sechelt District Municipality',
    'Fort Nelson': 'Nelson'
})

In [173]:
df_surgical_waitTime_Cleaned[df_surgical_waitTime_Cleaned['City'] == 'One Hundred Mile House'].head()

,HEALTH_AUTHORITY,HOSPITAL_NAME,PROCEDURE_GROUP,COMPLETED_50TH_PERCENTILE,COMPLETED_90TH_PERCENTILE,Calendar_Year,City,WAITING_INT,COMPLETED_INT
579,Interior,100 Mile District General Hospital,Dental Surgery,15.8,27.7,2010,One Hundred Mile House,10,30
580,Interior,100 Mile District General Hospital,Hernia Repair - Abdominal,0.0,0.0,2010,One Hundred Mile House,5,5
2856,Interior,100 Mile District General Hospital,Dental Surgery,14.1,24.5,2011,One Hundred Mile House,14,27
5167,Interior,100 Mile District General Hospital,Dental Surgery,16.4,35.3,2012,One Hundred Mile House,9,31
5168,Interior,100 Mile District General Hospital,Other Orthopaedic Surgery,0.0,0.0,2012,One Hundred Mile House,5,5

In [174]:
print(df_Comb_pop['Name'].unique())

['Abbotsford' 'Alert Bay' 'Anmore' 'Armstrong' 'Ashcroft' 'Barriere'
 'Belcarra' 'Bowen Island' 'Burnaby' 'Burns Lake' 'Cache Creek'
 'Campbell River' 'Canal Flats' 'Castlegar' 'Central Saanich' 'Chase'
 'Chetwynd' 'Chilliwack' 'Clearwater' 'Clinton' 'Coldstream' 'Colwood'
 'Comox' 'Coquitlam' 'Courtenay' 'Cranbrook' 'Creston' 'Cumberland'
 'Daajing Giids' 'Dawson Creek' 'Delta' 'Duncan' 'Elkford' 'Enderby'
 'Esquimalt' 'Fernie' 'Fort St. James' 'Fort St. John' 'Fraser Lake'
 'Fruitvale' 'Gibsons' 'Gold River' 'Golden' 'Grand Forks' 'Granisle'
 'Greenwood' 'Harrison Hot Springs' 'Hazelton' 'Highlands' 'Hope'
 'Houston' "Hudson's Hope" 'Invermere' 'Kamloops' 'Kaslo' 'Kelowna' 'Kent'
 'Keremeos' 'Kimberley' 'Kitimat' 'Ladysmith' 'Lake Country'
 'Lake Cowichan' 'Langford' 'Langley, City of'
 'Langley, District Municipality' 'Lantzville' 'Lillooet' 'Lions Bay'
 'Logan Lake' 'Lumby' 'Lytton' 'Mackenzie' 'Maple Ridge' 'Masset'
 'McBride' 'Merritt' 'Metchosin' 'Midway' 'Mission' 'Montrose' 'Nakusp'
 'Nanaimo' 'Nelson' 'New Denver' 'New Hazelton' 'New Westminster'
 'North Cowichan' 'North Saanich' 'North Vancouver, City of'
 'North Vancouver, District Municipality'
 'Northern Rockies Regional Municipality' 'Oak Bay' 'Oliver'
 'One Hundred Mile House' 'Osoyoos' 'Parksville' 'Peachland' 'Pemberton'
 'Penticton' 'Pitt Meadows' 'Port Alberni' 'Port Alice' 'Port Clements'
 'Port Coquitlam' 'Port Edward' 'Port Hardy' 'Port McNeill' 'Port Moody'
 'Pouce Coupe' 'Powell River' 'Prince George' 'Prince Rupert' 'Princeton'
 'Qualicum Beach' 'Quesnel' 'Radium Hot Springs' 'Revelstoke' 'Richmond'
 'Rossland' 'Saanich' 'Salmo' 'Salmon Arm' 'Sayward'
 'Sechelt District Municipality'
 'Sechelt Ind Gov Dist (Part-Sunshine Coast)'
 'Sechelt Ind Gov Dist (Part-qathet)' 'Sicamous' 'Sidney' 'Silverton'
 'Slocan' 'Smithers' 'Sooke' 'Spallumcheen' 'Sparwood' 'Squamish'
 'Stewart' 'Summerland' 'Sun Peaks Mountain' 'Surrey' 'Tahsis' 'Taylor'
 'Telkwa' 'Terrace' 'Tofino' 'Trail' 'Tumbler Ridge' 'Ucluelet'
 'Valemount' 'Vancouver' 'Vanderhoof' 'Vernon' 'Victoria' 'View Royal'
 'Warfield' 'Wells' 'West Kelowna' 'West Vancouver' 'Whistler'
 'White Rock' 'Williams Lake']

In [175]:
print(df_pop_2011_2024['Name'].unique())
#df_pop_2011_2024

['Abbotsford' 'Alert Bay' 'Anmore' 'Armstrong' 'Ashcroft' 'Barriere'
 'Belcarra' 'Bowen Island' 'Burnaby' 'Burns Lake' 'Cache Creek'
 'Campbell River' 'Canal Flats' 'Castlegar' 'Central Saanich' 'Chase'
 'Chetwynd' 'Chilliwack' 'Clearwater' 'Clinton' 'Coldstream' 'Colwood'
 'Comox' 'Coquitlam' 'Courtenay' 'Cranbrook' 'Creston' 'Cumberland'
 'Daajing Giids' 'Dawson Creek' 'Delta' 'Duncan' 'Elkford' 'Enderby'
 'Esquimalt' 'Fernie' 'Fort St. James' 'Fort St. John' 'Fraser Lake'
 'Fruitvale' 'Gibsons' 'Gold River' 'Golden' 'Grand Forks' 'Granisle'
 'Greenwood' 'Harrison Hot Springs' 'Hazelton' 'Highlands' 'Hope'
 'Houston' "Hudson's Hope" 'Invermere' 'Kamloops' 'Kaslo' 'Kelowna' 'Kent'
 'Keremeos' 'Kimberley' 'Kitimat' 'Ladysmith' 'Lake Country'
 'Lake Cowichan' 'Langford' 'Langley, City of'
 'Langley, District Municipality' 'Lantzville' 'Lillooet' 'Lions Bay'
 'Logan Lake' 'Lumby' 'Lytton' 'Mackenzie' 'Maple Ridge' 'Masset'
 'McBride' 'Merritt' 'Metchosin' 'Midway' 'Mission' 'Montrose' 'Nakusp'
 'Nanaimo' 'Nelson' 'New Denver' 'New Hazelton' 'New Westminster'
 'North Cowichan' 'North Saanich' 'North Vancouver, City of'
 'North Vancouver, District Municipality'
 'Northern Rockies Regional Municipality' 'Oak Bay' 'Oliver'
 'One Hundred Mile House' 'Osoyoos' 'Parksville' 'Peachland' 'Pemberton'
 'Penticton' 'Pitt Meadows' 'Port Alberni' 'Port Alice' 'Port Clements'
 'Port Coquitlam' 'Port Edward' 'Port Hardy' 'Port McNeill' 'Port Moody'
 'Pouce Coupe' 'Powell River' 'Prince George' 'Prince Rupert' 'Princeton'
 'Qualicum Beach' 'Quesnel' 'Radium Hot Springs' 'Revelstoke' 'Richmond'
 'Rossland' 'Saanich' 'Salmo' 'Salmon Arm' 'Sayward'
 'Sechelt District Municipality'
 'Sechelt Ind Gov Dist (Part-Sunshine Coast)'
 'Sechelt Ind Gov Dist (Part-qathet)' 'Sicamous' 'Sidney' 'Silverton'
 'Slocan' 'Smithers' 'Sooke' 'Spallumcheen' 'Sparwood' 'Squamish'
 'Stewart' 'Summerland' 'Sun Peaks Mountain' 'Surrey' 'Tahsis' 'Taylor'
 'Telkwa' 'Terrace' 'Tofino' 'Trail' 'Tumbler Ridge' 'Ucluelet'
 'Valemount' 'Vancouver' 'Vanderhoof' 'Vernon' 'Victoria' 'View Royal'
 'Warfield' 'Wells' 'West Kelowna' 'West Vancouver' 'Whistler'
 'White Rock' 'Williams Lake']

In [176]:
#Combine the rows of Names 'Langley, City of' and 'Langley, Township of' into 'Langley' in df_Comb_pop
df_Comb_pop['Name'] = df_Comb_pop['Name'].replace({ 'Langley, City of' : 'Langley', 'Langley, District Municipality' : 'Langley' })
df_Comb_pop['Name'] = df_Comb_pop['Name'].replace({ 'North Vancouver, City of' : 'North Vancouver', 'North Vancouver, District Municipality' : 'North Vancouver' })
df_Comb_pop['Name'] = df_Comb_pop['Name'].replace({
    'Sechelt Ind Gov Dist (Part-Sunshine Coast)' : 'Sechelt District Municipality',
    'Sechelt Ind Gov Dist (Part-qathet)':'Sechelt District Municipality'
})

In [177]:
#Top combine the data based on Name and Area Type, update the 'Area Type' of Langley, Sechelt District Municipality & North Vancouver to 'City'
df_Comb_pop.loc[df_Comb_pop['Name'] == 'Langley', 'Area Type'] = 'City'
df_Comb_pop.loc[df_Comb_pop['Name'] == 'Sechelt District Municipality', 'Area Type'] = 'City'
df_Comb_pop.loc[df_Comb_pop['Name'] == 'North Vancouver', 'Area Type'] = 'City'

In [178]:
print(df_Comb_pop['Name'].unique())

['Abbotsford' 'Alert Bay' 'Anmore' 'Armstrong' 'Ashcroft' 'Barriere'
 'Belcarra' 'Bowen Island' 'Burnaby' 'Burns Lake' 'Cache Creek'
 'Campbell River' 'Canal Flats' 'Castlegar' 'Central Saanich' 'Chase'
 'Chetwynd' 'Chilliwack' 'Clearwater' 'Clinton' 'Coldstream' 'Colwood'
 'Comox' 'Coquitlam' 'Courtenay' 'Cranbrook' 'Creston' 'Cumberland'
 'Daajing Giids' 'Dawson Creek' 'Delta' 'Duncan' 'Elkford' 'Enderby'
 'Esquimalt' 'Fernie' 'Fort St. James' 'Fort St. John' 'Fraser Lake'
 'Fruitvale' 'Gibsons' 'Gold River' 'Golden' 'Grand Forks' 'Granisle'
 'Greenwood' 'Harrison Hot Springs' 'Hazelton' 'Highlands' 'Hope'
 'Houston' "Hudson's Hope" 'Invermere' 'Kamloops' 'Kaslo' 'Kelowna' 'Kent'
 'Keremeos' 'Kimberley' 'Kitimat' 'Ladysmith' 'Lake Country'
 'Lake Cowichan' 'Langford' 'Langley' 'Lantzville' 'Lillooet' 'Lions Bay'
 'Logan Lake' 'Lumby' 'Lytton' 'Mackenzie' 'Maple Ridge' 'Masset'
 'McBride' 'Merritt' 'Metchosin' 'Midway' 'Mission' 'Montrose' 'Nakusp'
 'Nanaimo' 'Nelson' 'New Denver' 'New Hazelton' 'New Westminster'
 'North Cowichan' 'North Saanich' 'North Vancouver'
 'Northern Rockies Regional Municipality' 'Oak Bay' 'Oliver'
 'One Hundred Mile House' 'Osoyoos' 'Parksville' 'Peachland' 'Pemberton'
 'Penticton' 'Pitt Meadows' 'Port Alberni' 'Port Alice' 'Port Clements'
 'Port Coquitlam' 'Port Edward' 'Port Hardy' 'Port McNeill' 'Port Moody'
 'Pouce Coupe' 'Powell River' 'Prince George' 'Prince Rupert' 'Princeton'
 'Qualicum Beach' 'Quesnel' 'Radium Hot Springs' 'Revelstoke' 'Richmond'
 'Rossland' 'Saanich' 'Salmo' 'Salmon Arm' 'Sayward'
 'Sechelt District Municipality' 'Sicamous' 'Sidney' 'Silverton' 'Slocan'
 'Smithers' 'Sooke' 'Spallumcheen' 'Sparwood' 'Squamish' 'Stewart'
 'Summerland' 'Sun Peaks Mountain' 'Surrey' 'Tahsis' 'Taylor' 'Telkwa'
 'Terrace' 'Tofino' 'Trail' 'Tumbler Ridge' 'Ucluelet' 'Valemount'
 'Vancouver' 'Vanderhoof' 'Vernon' 'Victoria' 'View Royal' 'Warfield'
 'Wells' 'West Kelowna' 'West Vancouver' 'Whistler' 'White Rock'
 'Williams Lake']

In [179]:
# Group by 'Name' and 'Area Type', and sum all other numeric columns.
df_combPop_aggregated = (
    df_Comb_pop
    .groupby(['Name', 'Area Type'])
    .sum()
    .reset_index()
)

In [180]:
#Rename the column 'Name' to 'City' in df_combPop_aggregated so that We can merge with surgical wait time data
df_combPop_aggregated = df_combPop_aggregated.rename(columns={'Name': 'City'})


df_combPop_aggregated.iloc[118:140]

,City,Area Type,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
118,Saanich,District Municipality,108170.0,108687.0,109186.0,109647.0,110395.0,111422.0,111192.0,111641.0,...,116881.0,119209.0,119841.0,120312.0,121795.0,122584.0,122889.0,123979.0,124667.0,125436.0
119,Salmo,Village,1163.0,1121.0,1090.0,1072.0,1045.0,1035.0,1092.0,1118.0,...,1158.0,1174.0,1203.0,1153.0,1193.0,1213.0,1171.0,1237.0,1206.0,1234.0
120,Salmon Arm,City,15806.0,15815.0,15881.0,15930.0,16100.0,16403.0,16893.0,17300.0,...,17936.0,18319.0,18849.0,19114.0,19365.0,19644.0,20081.0,20449.0,20620.0,20613.0
121,Sayward,Village,392.0,382.0,372.0,364.0,356.0,349.0,343.0,340.0,...,291.0,325.0,342.0,360.0,375.0,366.0,346.0,351.0,353.0,363.0
122,Sechelt District Municipality,City,8945.0,9041.0,9152.0,9266.0,9400.0,9431.0,9654.0,9984.0,...,10865.0,11228.0,11400.0,11571.0,11628.0,11824.0,11939.0,12262.0,12231.0,12309.0
123,Sicamous,District Municipality,2818.0,2782.0,2768.0,2740.0,2731.0,2720.0,2680.0,2646.0,...,2470.0,2509.0,2555.0,2601.0,2718.0,2658.0,2695.0,2762.0,2818.0,2841.0
124,Sidney,Town,11293.0,11332.0,11383.0,11419.0,11470.0,11488.0,11417.0,11551.0,...,11733.0,12004.0,12193.0,12354.0,12382.0,12531.0,12614.0,13049.0,13219.0,13288.0
125,Silverton,Village,229.0,222.0,217.0,207.0,197.0,187.0,189.0,191.0,...,197.0,198.0,196.0,194.0,191.0,188.0,185.0,189.0,193.0,197.0
126,Slocan,Village,350.0,340.0,337.0,330.0,323.0,320.0,315.0,310.0,...,300.0,302.0,319.0,339.0,357.0,375.0,391.0,398.0,407.0,416.0
127,Smithers,Town,5636.0,5519.0,5454.0,5444.0,5377.0,5363.0,5408.0,5435.0,...,5574.0,5622.0,5579.0,5599.0,5624.0,5623.0,5620.0,5636.0,5657.0,5661.0
128,Sooke,District Municipality,9114.0,9255.0,9405.0,9563.0,9747.0,9995.0,10285.0,10613.0,...,13069.0,13623.0,14109.0,14485.0,14803.0,15236.0,15712.0,16475.0,16897.0,17128.0
129,Spallumcheen,District Municipality,5317.0,5249.0,5215.0,5179.0,5156.0,5061.0,5089.0,5139.0,...,5179.0,5302.0,5467.0,5420.0,5474.0,5432.0,5490.0,5911.0,6040.0,5779.0
130,Sparwood,District Municipality,3963.0,3911.0,3851.0,3781.0,3735.0,3728.0,3795.0,3841.0,...,3970.0,3946.0,3995.0,4106.0,4193.0,4230.0,4345.0,4431.0,4443.0,4423.0
131,Squamish,District Municipality,14775.0,14966.0,15104.0,15255.0,15237.0,15378.0,16377.0,16665.0,...,19515.0,20579.0,21422.0,22017.0,22604.0,23631.0,25063.0,25602.0,26561.0,28056.0
132,Stewart,District Municipality,686.0,648.0,608.0,572.0,534.0,505.0,505.0,486.0,...,431.0,419.0,440.0,463.0,487.0,512.0,539.0,561.0,520.0,528.0
133,Summerland,District Municipality,11138.0,11144.0,11120.0,11153.0,11097.0,11053.0,11281.0,11392.0,...,11970.0,11936.0,12093.0,12128.0,12167.0,12259.0,12426.0,12605.0,12489.0,12492.0
134,Sun Peaks Mountain,Village,405.0,411.0,417.0,422.0,427.0,435.0,431.0,424.0,...,617.0,680.0,836.0,1028.0,1227.0,1364.0,1467.0,1502.0,1537.0,1561.0
135,Surrey,City,363639.0,372838.0,380957.0,389103.0,398740.0,409229.0,420626.0,434198.0,...,530349.0,543495.0,553188.0,563844.0,578429.0,589554.0,597141.0,619230.0,655660.0,700459.0
136,Tahsis,Village,620.0,558.0,508.0,457.0,414.0,375.0,366.0,357.0,...,275.0,257.0,280.0,320.0,357.0,391.0,401.0,387.0,377.0,378.0
137,Taylor,District Municipality,1199.0,1235.0,1277.0,1320.0,1368.0,1442.0,1437.0,1414.0,...,1522.0,1538.0,1505.0,1478.0,1448.0,1413.0,1380.0,1410.0,1418.0,1431.0
138,Telkwa,Village,1428.0,1396.0,1380.0,1373.0,1353.0,1326.0,1313.0,1328.0,...,1361.0,1393.0,1433.0,1460.0,1483.0,1518.0,1543.0,1547.0,1552.0,1552.0
139,Terrace,City,12618.0,12324.0,12086.0,11914.0,11749.0,11617.0,11698.0,11721.0,...,12134.0,12105.0,12126.0,12226.0,12258.0,12533.0,12604.0,12718.0,12970.0,13252.0

In [ ]:
year_columns = [col for col in df_combPop_aggregated.columns if str(col).isdigit() and 2001 <= int(col) <= 2024]

# 2. MELT the population DataFrame to long format
df_pop_long = pd.melt(
    df_combPop_aggregated,
    id_vars=['City'],                          # Keep 'City' as the main identifier
    value_vars=year_columns,                   # These are the columns to melt (the population years)
    var_name='Calendar_Year',                  # Name the new column holding the year values
    value_name='Population'                    # Name the new column holding the population counts
)

# 3. Ensure 'Calendar_Year' is an integer to match the surgical data
df_pop_long['Calendar_Year'] = pd.to_numeric(df_pop_long['Calendar_Year'], errors='coerce').astype('Int64')

print(df_pop_long.head())

         City  Calendar_Year  Population
0  Abbotsford           2001    121125.0
1   Alert Bay           2001       584.0
2      Anmore           2001      1406.0
3   Armstrong           2001      4445.0
4    Ashcroft           2001      1871.0

In [182]:
#Merge the Population Data with Surgical Wait Time Data on 'City' column left join so that we retain all surgical wait time records hospital wise and get population data where available
df_Popltn_SurgWt_combined = pd.merge(df_surgical_waitTime_Cleaned, df_pop_long, on=['City','Calendar_Year'], how='left')

In [183]:
df_Popltn_SurgWt_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42204 entries, 0 to 42203
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   HEALTH_AUTHORITY           42204 non-null  object
 1   HOSPITAL_NAME              42204 non-null  object
 2   PROCEDURE_GROUP            42204 non-null  object
 3   COMPLETED_50TH_PERCENTILE  42204 non-null  float64
 4   COMPLETED_90TH_PERCENTILE  42204 non-null  float64
 5   Calendar_Year              42204 non-null  int64
 6   City                       42204 non-null  object
 7   WAITING_INT                42204 non-null  int64
 8   COMPLETED_INT              42204 non-null  int64
 9   Population                 42204 non-null  float64
dtypes: float64(3), int64(3), object(4)
memory usage: 3.2+ MB

In [184]:
df_Popltn_SurgWt_combined.head()

,HEALTH_AUTHORITY,HOSPITAL_NAME,PROCEDURE_GROUP,COMPLETED_50TH_PERCENTILE,COMPLETED_90TH_PERCENTILE,Calendar_Year,City,WAITING_INT,COMPLETED_INT,Population
0,Fraser,Abbotsford Regional Hospital And Cancer Centre,Abdominoplasty,0.0,0.0,2010,Abbotsford,10,5,135168.0
1,Fraser,Abbotsford Regional Hospital And Cancer Centre,All Other Procedures,4.0,34.2,2010,Abbotsford,30,59,135168.0
2,Fraser,Abbotsford Regional Hospital And Cancer Centre,Aortic Aneurysm Repair,5.1,12.1,2010,Abbotsford,18,14,135168.0
3,Fraser,Abbotsford Regional Hospital And Cancer Centre,Appendectomy,0.0,0.0,2010,Abbotsford,5,5,135168.0
4,Fraser,Abbotsford Regional Hospital And Cancer Centre,Biopsy in OR,1.9,8.8,2010,Abbotsford,6,37,135168.0

In [185]:
output_path = "../00_data/df_Popltn_SurgWt_combined.parquet"
df_Popltn_SurgWt_combined.to_parquet(output_path, index=False)